// Builds a color theme from the colors in colors.mjs. The brand rules shape it
// (.handbook/conventions/reference/brand.md):
//
// - Pink means focus, the active item and the primary action: the cursor, the active tab's top
//   line, focus outlines, buttons and badges. Everything else is graphite and gray.
// - Fills use the accent; lines use the accent edge, which light mode deepens to deep rose.
// - Text on pink is graphite. Pink is never text on a light background.
// - Selections are a pink tint, at the strength the palette allows for text on it.

import { colors } from "./colors.mjs";

/** `#rrggbb` plus an alpha channel, from a fraction or a percentage string like `35%`. */
export function withAlpha(hex, amount) {
  const fraction = typeof amount === "string" ? parseFloat(amount) / 100 : amount;
  return hex + Math.round(fraction * 255).toString(16).padStart(2, "0");
}

function interfaceColors(c) {
  const dark = c.scheme === "dark";
  const tint = withAlpha(c.accent, c.tintStrength);
  // Pink as text: pastel on graphite, deep rose on light (brand rule).
  const pinkText = c.pink;
  const activeLineNumber = dark ? c.accent : c.text;
  const shadow = dark ? "#00000059" : "#0000001f";

  return {
    // Base
    focusBorder: c.focus,
    foreground: c.text,
    descriptionForeground: c.muted,
    disabledForeground: c.muted,
    errorForeground: c.rose,
    "icon.foreground": c.text,
    "selection.background": tint,
    "textLink.foreground": c.blue,
    "textLink.activeForeground": pinkText,
    "textBlockQuote.background": c.surface,
    "textBlockQuote.border": c.border,
    "textCodeBlock.background": c.surface,
    "textPreformat.foreground": c.text,
    "textPreformat.background": c.surface,
    "textSeparator.foreground": c.border,
    "widget.shadow": shadow,
    "widget.border": c.border,
    "sash.hoverBorder": c.accentEdge,
    "window.activeBorder": c.border,
    "window.inactiveBorder": c.border,

    // Title bar, activity bar, side bar
    "titleBar.activeBackground": c.bg,
    "titleBar.activeForeground": c.text,
    "titleBar.inactiveBackground": c.bg,
    "titleBar.inactiveForeground": c.muted,
    "titleBar.border": c.border,
    "activityBar.background": c.bg,
    "activityBar.foreground": c.text,
    "activityBar.inactiveForeground": c.muted,
    "activityBar.activeBorder": c.accentEdge,
    "activityBar.border": c.border,
    "activityBarBadge.background": c.accent,
    "activityBarBadge.foreground": c.onAccent,
    "sideBar.background": c.bg,
    "sideBar.foreground": c.text,
    "sideBar.border": c.border,
    "sideBarTitle.foreground": c.text,
    "sideBarSectionHeader.background": c.bg,
    "sideBarSectionHeader.foreground": c.text,
    "sideBarSectionHeader.border": c.border,

    // Lists and trees
    "list.activeSelectionBackground": c.elevated,
    "list.activeSelectionForeground": c.text,
    "list.activeSelectionIconForeground": c.text,
    "list.inactiveSelectionBackground": c.surface,
    "list.inactiveSelectionForeground": c.text,
    "list.hoverBackground": c.surface,
    "list.hoverForeground": c.text,
    "list.focusOutline": c.focus,
    "list.focusAndSelectionOutline": c.focus,
    "list.inactiveFocusOutline": c.border,
    "list.highlightForeground": pinkText,
    "list.focusHighlightForeground": pinkText,
    "list.errorForeground": c.rose,
    "list.warningForeground": c.sand,
    "list.dropBackground": tint,
    "tree.indentGuidesStroke": c.border,
    "tree.inactiveIndentGuidesStroke": c.border,

    // Editor
    "editor.background": c.bg,
    "editor.foreground": c.text,
    "editorLineNumber.foreground": c.muted,
    "editorLineNumber.activeForeground": activeLineNumber,
    "editorCursor.foreground": c.focus,
    "editorCursor.background": c.bg,
    "editor.lineHighlightBackground": dark ? c.surface : c.elevated,
    "editor.lineHighlightBorder": "#00000000",
    "editor.selectionBackground": tint,
    "editor.inactiveSelectionBackground": withAlpha(c.accent, parseFloat(c.tintStrength) / 200),
    "editor.selectionHighlightBackground": withAlpha(c.accent, 0.15),
    "editor.selectionHighlightBorder": withAlpha(c.accentEdge, 0.5),
    "editor.wordHighlightBackground": withAlpha(c.muted, 0.15),
    "editor.wordHighlightStrongBackground": withAlpha(c.muted, 0.25),
    "editor.findMatchBackground": withAlpha(c.sand, 0.35),
    "editor.findMatchBorder": c.sand,
    "editor.findMatchHighlightBackground": withAlpha(c.sand, 0.18),
    "editor.findRangeHighlightBackground": withAlpha(c.muted, 0.1),
    "editor.rangeHighlightBackground": withAlpha(c.muted, 0.1),
    "editor.foldBackground": withAlpha(c.muted, 0.08),
    "editorLink.activeForeground": c.blue,
    "editorIndentGuide.background1": c.border,
    "editorIndentGuide.activeBackground1": c.muted,
    "editorWhitespace.foreground": c.border,
    "editorRuler.foreground": c.border,
    "editorCodeLens.foreground": c.muted,
    "editorInlayHint.foreground": c.muted,
    "editorInlayHint.background": c.surface,
    "editorBracketMatch.background": withAlpha(c.muted, 0.15),
    "editorBracketMatch.border": c.muted,
    "editorBracketHighlight.foreground1": c.pink,
    "editorBracketHighlight.foreground2": c.blue,
    "editorBracketHighlight.foreground3": c.teal,
    "editorBracketHighlight.foreground4": c.sand,
    "editorBracketHighlight.foreground5": c.sage,
    "editorBracketHighlight.foreground6": c.rose,
    "editorBracketHighlight.unexpectedBracket.foreground": c.rose,
    "editorError.foreground": c.rose,
    "editorWarning.foreground": c.sand,
    "editorInfo.foreground": c.blue,
    "editorHint.foreground": c.teal,
    "editorUnnecessaryCode.opacity": "#000000a0",
    "editorGutter.background": c.bg,
    "editorGutter.addedBackground": c.sage,
    "editorGutter.modifiedBackground": c.blue,
    "editorGutter.deletedBackground": c.rose,
    "editorGutter.foldingControlForeground": c.muted,
    "editorOverviewRuler.border": c.border,
    "editorOverviewRuler.addedForeground": c.sage,
    "editorOverviewRuler.modifiedForeground": c.blue,
    "editorOverviewRuler.deletedForeground": c.rose,
    "editorOverviewRuler.errorForeground": c.rose,
    "editorOverviewRuler.warningForeground": c.sand,
    "editorOverviewRuler.findMatchForeground": c.sand,
    "editorStickyScroll.background": c.bg,
    "editorStickyScroll.shadow": shadow,
    "diffEditor.insertedTextBackground": withAlpha(c.sage, 0.22),
    "diffEditor.removedTextBackground": withAlpha(c.rose, 0.22),
    "diffEditor.insertedLineBackground": withAlpha(c.sage, 0.1),
    "diffEditor.removedLineBackground": withAlpha(c.rose, 0.1),
    "diffEditor.diagonalFill": c.border,

    // Editor groups and tabs: every tab sits on the background; the active one gets the pink line
    "editorGroup.border": c.border,
    "editorGroupHeader.tabsBackground": c.bg,
    "editorGroupHeader.tabsBorder": c.border,
    "editorGroupHeader.noTabsBackground": c.bg,
    "editorGroup.dropBackground": tint,
    "tab.activeBackground": c.bg,
    "tab.activeForeground": c.text,
    "tab.activeBorderTop": c.accentEdge,
    "tab.activeBorder": c.bg,
    "tab.inactiveBackground": c.bg,
    "tab.inactiveForeground": c.muted,
    "tab.unfocusedActiveBackground": c.bg,
    "tab.unfocusedActiveForeground": c.text,
    "tab.unfocusedActiveBorderTop": c.border,
    "tab.unfocusedInactiveForeground": c.muted,
    "tab.hoverBackground": c.surface,
    "tab.border": c.border,
    "breadcrumb.background": c.bg,
    "breadcrumb.foreground": c.muted,
    "breadcrumb.focusForeground": c.text,
    "breadcrumb.activeSelectionForeground": c.text,
    "breadcrumbPicker.background": c.surface,

    // Widgets: find, suggestions, hovers, peek
    "editorWidget.background": c.surface,
    "editorWidget.foreground": c.text,
    "editorWidget.border": c.border,
    "editorSuggestWidget.background": c.surface,
    "editorSuggestWidget.foreground": c.text,
    "editorSuggestWidget.border": c.border,
    "editorSuggestWidget.selectedBackground": c.elevated,
    "editorSuggestWidget.selectedForeground": c.text,
    "editorSuggestWidget.highlightForeground": pinkText,
    "editorSuggestWidget.focusHighlightForeground": pinkText,
    "editorHoverWidget.background": c.surface,
    "editorHoverWidget.foreground": c.text,
    "editorHoverWidget.border": c.border,
    "peekView.border": c.accentEdge,
    "peekViewTitle.background": c.elevated,
    "peekViewTitleLabel.foreground": c.text,
    "peekViewTitleDescription.foreground": c.muted,
    "peekViewEditor.background": c.surface,
    "peekViewEditor.matchHighlightBackground": withAlpha(c.sand, 0.35),
    "peekViewResult.background": c.surface,
    "peekViewResult.fileForeground": c.text,
    "peekViewResult.lineForeground": c.muted,
    "peekViewResult.selectionBackground": c.elevated,
    "peekViewResult.selectionForeground": c.text,
    "peekViewResult.matchHighlightBackground": withAlpha(c.sand, 0.35),

    // Controls
    "input.background": c.elevated,
    "input.foreground": c.text,
    "input.border": c.border,
    "input.placeholderForeground": c.muted,
    "inputOption.activeBackground": tint,
    "inputOption.activeBorder": c.accentEdge,
    "inputOption.activeForeground": c.text,
    "inputValidation.errorBackground": c.surface,
    "inputValidation.errorBorder": c.rose,
    "inputValidation.errorForeground": c.text,
    "inputValidation.warningBackground": c.surface,
    "inputValidation.warningBorder": c.sand,
    "inputValidation.warningForeground": c.text,
    "inputValidation.infoBackground": c.surface,
    "inputValidation.infoBorder": c.blue,
    "inputValidation.infoForeground": c.text,
    "dropdown.background": c.elevated,
    "dropdown.listBackground": c.surface,
    "dropdown.foreground": c.text,
    "dropdown.border": c.border,
    "checkbox.background": c.elevated,
    "checkbox.foreground": c.text,
    "checkbox.border": c.muted,
    "checkbox.selectBorder": c.accentEdge,
    "button.background": c.accent,
    "button.foreground": c.onAccent,
    "button.hoverBackground": dark ? "#ffd7de" : "#fdb0bd",
    "button.border": "#00000000",
    "button.separator": withAlpha(c.onAccent, 0.4),
    "button.secondaryBackground": c.elevated,
    "button.secondaryForeground": c.text,
    "button.secondaryHoverBackground": c.border,
    "badge.background": c.accent,
    "badge.foreground": c.onAccent,
    "progressBar.background": c.accentEdge,
    "scrollbar.shadow": shadow,
    "scrollbarSlider.background": withAlpha(c.muted, 0.25),
    "scrollbarSlider.hoverBackground": withAlpha(c.muted, 0.4),
    "scrollbarSlider.activeBackground": withAlpha(c.muted, 0.55),
    "keybindingLabel.background": c.elevated,
    "keybindingLabel.foreground": c.text,
    "keybindingLabel.border": c.border,
    "keybindingLabel.bottomBorder": c.border,
    "settings.headerForeground": c.text,
    "settings.modifiedItemIndicator": c.accentEdge,
    "settings.focusedRowBackground": c.surface,
    "settings.focusedRowBorder": c.focus,

    // Menus, quick input, notifications
    "menu.background": c.surface,
    "menu.foreground": c.text,
    "menu.border": c.border,
    "menu.selectionBackground": c.elevated,
    "menu.selectionForeground": c.text,
    "menu.separatorBackground": c.border,
    "menubar.selectionBackground": c.surface,
    "menubar.selectionForeground": c.text,
    "quickInput.background": c.surface,
    "quickInput.foreground": c.text,
    "quickInputList.focusBackground": c.elevated,
    "quickInputList.focusForeground": c.text,
    "quickInputTitle.background": c.elevated,
    "pickerGroup.foreground": pinkText,
    "pickerGroup.border": c.border,
    "notifications.background": c.surface,
    "notifications.foreground": c.text,
    "notifications.border": c.border,
    "notificationCenterHeader.background": c.elevated,
    "notificationCenterHeader.foreground": c.text,
    "notificationsErrorIcon.foreground": c.rose,
    "notificationsWarningIcon.foreground": c.sand,
    "notificationsInfoIcon.foreground": c.blue,
    "notificationLink.foreground": c.blue,

    // Panel and status bar
    "panel.background": c.bg,
    "panel.border": c.border,
    "panelTitle.activeForeground": c.text,
    "panelTitle.activeBorder": c.accentEdge,
    "panelTitle.inactiveForeground": c.muted,
    "panelSection.border": c.border,
    "panelInput.border": c.border,
    "statusBar.background": c.bg,
    "statusBar.foreground": c.muted,
    "statusBar.border": c.border,
    "statusBar.focusBorder": c.focus,
    "statusBar.noFolderBackground": c.bg,
    "statusBar.noFolderForeground": c.muted,
    "statusBar.debuggingBackground": c.accent,
    "statusBar.debuggingForeground": c.onAccent,
    "statusBar.debuggingBorder": c.border,
    "statusBarItem.hoverBackground": c.surface,
    "statusBarItem.hoverForeground": c.text,
    "statusBarItem.activeBackground": c.elevated,
    "statusBarItem.remoteBackground": c.accent,
    "statusBarItem.remoteForeground": c.onAccent,
    "statusBarItem.remoteHoverBackground": dark ? "#ffd7de" : "#fdb0bd",
    "statusBarItem.remoteHoverForeground": c.onAccent,
    "statusBarItem.prominentBackground": c.elevated,
    "statusBarItem.prominentForeground": c.text,
    "statusBarItem.errorBackground": c.bg,
    "statusBarItem.errorForeground": c.rose,
    "statusBarItem.warningBackground": c.bg,
    "statusBarItem.warningForeground": c.sand,

    // Integrated terminal: the Rhodonite terminal colors
    "terminal.background": c.bg,
    "terminal.foreground": c.text,
    "terminal.border": c.border,
    "terminal.selectionBackground": tint,
    "terminalCursor.foreground": c.focus,
    "terminalCursor.background": c.bg,
    ...Object.fromEntries(
      Object.entries(c.terminal).map(([name, value]) => [
        `terminal.ansi${name[0].toUpperCase()}${name.slice(1)}`,
        value,
      ]),
    ),

    // Source control
    "gitDecoration.addedResourceForeground": c.sage,
    "gitDecoration.modifiedResourceForeground": c.blue,
    "gitDecoration.deletedResourceForeground": c.rose,
    "gitDecoration.renamedResourceForeground": c.teal,
    "gitDecoration.untrackedResourceForeground": c.teal,
    "gitDecoration.ignoredResourceForeground": c.muted,
    "gitDecoration.conflictingResourceForeground": c.sand,
    "gitDecoration.stageModifiedResourceForeground": c.blue,
    "gitDecoration.stageDeletedResourceForeground": c.rose,
    "gitDecoration.submoduleResourceForeground": c.muted,
    "merge.currentHeaderBackground": withAlpha(c.sage, 0.35),
    "merge.currentContentBackground": withAlpha(c.sage, 0.12),
    "merge.incomingHeaderBackground": withAlpha(c.blue, 0.35),
    "merge.incomingContentBackground": withAlpha(c.blue, 0.12),

    // Minimap
    "minimap.findMatchHighlight": c.sand,
    "minimap.selectionHighlight": c.accentEdge,
    "minimap.errorHighlight": c.rose,
    "minimap.warningHighlight": c.sand,
    "minimapGutter.addedBackground": c.sage,
    "minimapGutter.modifiedBackground": c.blue,
    "minimapGutter.deletedBackground": c.rose,
  };
}

function tokenColors(c) {
  const rule = (name, scope, settings) => ({ name, scope, settings });
  return [
    rule("Comments", ["comment", "punctuation.definition.comment", "string.comment"], { foreground: c.muted, fontStyle: "italic" }),
    rule("Keywords and storage", ["keyword", "storage.type", "storage.modifier", "keyword.operator.new", "keyword.operator.expression", "keyword.operator.logical.python", "keyword.operator.wordlike"], { foreground: c.pink }),
    rule("Operators and punctuation", ["keyword.operator", "punctuation", "meta.brace", "meta.delimiter"], { foreground: c.punctuation }),
    rule("Strings", ["string", "punctuation.definition.string", "markup.inline.raw"], { foreground: c.sage }),
    rule("Regular expressions and escapes", ["string.regexp", "constant.character.escape", "constant.other.placeholder"], { foreground: c.teal }),
    rule("Template expressions", ["punctuation.definition.template-expression", "punctuation.section.embedded"], { foreground: c.pink }),
    rule("Numbers and constants", ["constant.numeric", "constant.language", "constant.other", "support.constant", "variable.other.constant", "variable.other.enummember", "entity.name.constant"], { foreground: c.sand }),
    rule("Functions", ["entity.name.function", "support.function", "meta.function-call entity.name.function", "variable.function"], { foreground: c.blue }),
    rule("Types, classes and namespaces", ["entity.name.type", "entity.name.class", "entity.name.namespace", "entity.other.inherited-class", "support.type", "support.class", "storage.type.primitive", "storage.type.built-in", "storage.type.java", "storage.type.cs", "storage.type.rust", "storage.type.go"], { foreground: c.teal }),
    rule("Variables", ["variable", "variable.parameter", "variable.other", "meta.definition.variable"], { foreground: c.text }),
    rule("Language variables", ["variable.language", "variable.parameter.function.language.special"], { foreground: c.pink, fontStyle: "italic" }),
    rule("Properties and keys", ["support.type.property-name", "meta.object-literal.key", "entity.name.tag.yaml", "entity.name.tag.toml", "support.type.property-name.json"], { foreground: c.blue }),
    rule("Decorators and annotations", ["meta.decorator", "entity.name.function.decorator", "punctuation.decorator", "storage.type.annotation"], { foreground: c.sand }),
    rule("Tags", ["entity.name.tag", "punctuation.definition.tag"], { foreground: c.pink }),
    rule("Attributes", ["entity.other.attribute-name"], { foreground: c.sand, fontStyle: "italic" }),
    rule("CSS selectors", ["entity.other.attribute-name.class.css", "entity.other.attribute-name.id.css", "entity.name.tag.css"], { foreground: c.sand, fontStyle: "" }),
    rule("CSS values and units", ["support.constant.property-value", "keyword.other.unit", "constant.other.color"], { foreground: c.sand }),
    rule("Headings", ["markup.heading", "entity.name.section", "punctuation.definition.heading"], { foreground: c.pink, fontStyle: "bold" }),
    rule("Bold", ["markup.bold"], { fontStyle: "bold" }),
    rule("Italic", ["markup.italic"], { fontStyle: "italic" }),
    rule("Strikethrough", ["markup.strikethrough"], { fontStyle: "strikethrough" }),
    rule("Links", ["markup.underline.link", "string.other.link"], { foreground: c.blue }),
    rule("Quotes", ["markup.quote"], { foreground: c.muted, fontStyle: "italic" }),
    rule("List markers", ["punctuation.definition.list", "markup.list punctuation.definition"], { foreground: c.pink }),
    rule("Inserted", ["markup.inserted", "meta.diff.header.to-file"], { foreground: c.sage }),
    rule("Deleted", ["markup.deleted", "meta.diff.header.from-file"], { foreground: c.rose }),
    rule("Changed", ["markup.changed"], { foreground: c.sand }),
    rule("Diff ranges", ["meta.diff.range", "meta.diff.header"], { foreground: c.blue }),
    rule("Invalid", ["invalid", "invalid.illegal"], { foreground: c.rose }),
    rule("Deprecated", ["invalid.deprecated"], { foreground: c.rose, fontStyle: "strikethrough" }),
  ];
}

function semanticTokenColors(c) {
  return {
    keyword: c.pink,
    function: c.blue,
    method: c.blue,
    "function.defaultLibrary": c.blue,
    type: c.teal,
    class: c.teal,
    interface: c.teal,
    enum: c.teal,
    namespace: c.teal,
    typeParameter: c.teal,
    enumMember: c.sand,
    "variable.readonly": c.text,
    "variable.defaultLibrary": c.text,
    "property.readonly": c.text,
    parameter: c.text,
    property: c.text,
    decorator: c.sand,
    macro: c.sand,
    selfKeyword: { foreground: c.pink, italic: true },
    "*.deprecated": { strikethrough: true },
  };
}

export function buildTheme(scheme) {
  const c = colors(scheme);
  return {
    $schema: "vscode://schemas/color-theme",
    name: scheme === "dark" ? "Rhodonite" : "Rhodonite Light",
    type: scheme,
    semanticHighlighting: true,
    colors: interfaceColors(c),
    tokenColors: tokenColors(c),
    semanticTokenColors: semanticTokenColors(c),
  };
}

/** Each theme file, as `package.json` lists it. */
export const THEME_FILES = [
  { scheme: "dark", path: "themes/rhodonite-color-theme.json" },
  { scheme: "light", path: "themes/rhodonite-light-color-theme.json" },
];
